azure:
  activedirectory:
    b2c:
      base-uri: https://javapptest.b2clogin.com/javapptest.onmicrosoft.com/
      client-id: 484a8a7f-dd36-40f2-bfb5-858f9720eecc
      client-secret: )s8)6!?>0fLt2m6Y"vxJ285"
#      logout-success-url: ${you-logout-success-url}
      user-flows:
        sign-up-or-sign-in: B2C_1_sign_in_and_register_flow
#      user-name-attribute-name: ${your-user-name-attribute-name}

logging:
  level:
    root: DEBUG

jwt:
  secret:
    key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

